# Generated by Django 5.2.13 on 2026-04-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('expense_type', models.CharField(choices=[('electricity', 'Tiền điện'), ('water', 'Tiền nước'), ('rent', 'Tiền mặt bằng'), ('salary', 'Lương'), ('transport', 'Vận chuyển'), ('other', 'Khác')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('alert_threshold', models.PositiveIntegerField(default=10)),
                ('price_sell', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('price_buy_latest', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
