# Generated by Django 5.2.13 on 2026-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense_payment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='estimated_lifetime_months',
            field=models.IntegerField(blank=True, help_text='Sử dụng cho Mua thiết bị để tính khấu hao', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('electricity', 'Tiền điện'), ('water', 'Tiền nước'), ('rent', 'Tiền mặt bằng'), ('salary', 'Lương'), ('transport', 'Vận chuyển'), ('equipment', 'Mua thiết bị'), ('other', 'Khác')], max_length=50),
        ),
    ]
