# Generated by Django 5.2.13 on 2026-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_estimated_lifetime_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
