# Generated by Django 5.2.13 on 2026-06-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_openingstock_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='estimated_lifetime_months',
            field=models.IntegerField(blank=True, help_text='Số tháng dự kiến sử dụng hoặc hưởng lợi từ chi phí. Để trống = tính toàn bộ vào kỳ phát sinh.', null=True, verbose_name='Thời gian sử dụng (tháng)'),
        ),
    ]
