# Generated by Django 5.2.13 on 2026-06-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_expense_estimated_lifetime_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Mã sản phẩm tự động. Ví dụ: CF-001', max_length=20),
        ),
    ]
